config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"
  resources :grandmas do
    resources :bookings
  end
  get 'search_grandmas', to: 'grandmas#search', as: 'search_grandmas'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :grandma
  validates :grandma_id, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  
end

app/models/grandma.rb
class Grandma < ApplicationRecord
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
  belongs_to :user
  has_many :bookings

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :user_id, presence: true
  has_many :users, through: :bookings, dependent: :destroy
  has_one_attached :image_url
  has_many_attached :feed_photos, dependent: :destroy
  # validates :description, length: { minimum: 6 }
  #  validates :feed_photos, presence: true, length: { is: 3 }, format: { with: /\A(https?:\/\/.+\.([a-z]+\.)?[a-z]{2,}\/?.*\.jpg|jpeg|png)\z/i }, if: Proc.new { |g| g.feed_photos.present? }

  def self.search(query)
    where("name LIKE ?", "%#{query}%")
  end#
end

app/models/user.rb
class User < ApplicationRecord
  has_many :grandmas
  has_many :bookings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :grandmas, through: :bookings, dependent: :destroy
  has_one_attached :photo
#  validates :description, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new
    @grandma = Grandma.find(params[:grandma_id])
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @grandma = Grandma.find(params[:grandma_id])
    @booking.grandma = @grandma

    if @booking.save!
      redirect_to grandma_booking_path(@grandma, @booking)
    else
      render :new
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/grandmas_controller.rb
class GrandmasController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_grandma, only: [:show, :edit, :update, :destroy]

  def index
    @grandmas = Grandma.all
    @markers = @grandmas.geocoded.map do |grandma|
      {
        lat: grandma.latitude,
        lng: grandma.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {grandma: grandma})
      }
    end
  end

  def new
    @grandma = Grandma.new
  end

  def show
    @grandma
  end

  def edit
  end
  
  def search
    @grandmas = Grandma.search(params[:query])
  end

  def create
    @grandma = Grandma.new(grandma_params)
    @grandma.user = current_user
    if @grandma.save!
      redirect_to grandma_path(@grandma)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @grandma = Grandma.find(params[:id])
    if @grandma.update(grandma_params)
      redirect_to @grandma, notice: 'Grandma was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @grandma = Grandma.find(params[:id])
    @grandma.destroy
    redirect_to grandmas_path
  end

  private

  def grandma_params
    params.require(:grandma).permit(:first_name, :last_name, :location, :skills, :price, :description, :image_url, feed_photos: [])
  end

  def set_grandma
    @grandma = Grandma.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home






  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="container">
<h1>New Booking</h1>
<%= simple_form_for [@grandma, @booking] do |f| %>
  <%= f.input :start_date %>
  <%= f.input :end_date %>
  <%= f.submit "Reserve", class: "btn btn-primary" %>
<% end %>
</div>

app/views/bookings/show.hmtl.erb
<div class = "container">
<h1>Your booking with <%= @booking.grandma.first_name %> was created 🎉</h1>

<p> Details: </p>
<p>First Name <%= @booking.grandma.first_name  %></p>
<p>Last Name <%= @booking.grandma.last_name  %></p>
<p>Location <%= @booking.grandma.location  %></p>
<p>Total: <%= @booking.grandma.price  %></p>

<%= link_to "book another grandma", grandmas_path %>
</div>

app/views/bookings/show.html.erb
<div class = "container booking-success mt-3">
<h1>Your booking with <%= @booking.grandma.first_name %> was created 👵🏽🎉</h1>

<strong>Details:</strong>

<p >Reference: <%= @booking.grandma.last_name  %> - X5768 </p>
<p class="list-group-item list-group-item-dark"  >First Name: <%= @booking.grandma.first_name  %> <%= @booking.grandma.last_name  %></p>
<p>Location: <%= @booking.grandma.location  %></p>
<p class="list-group-item list-group-item-dark">Total: 55$</p>

<%= link_to "Book another Grandma", grandmas_path %>
</div>

app/views/grandma_ids/_form.html.erb
<%= simple_form_for(@grandma_id) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/grandma_ids/_grandma_id.html.erb
<div id="<%= dom_id grandma_id %>">
  <p>
    <strong>Name:</strong>
    <%= grandma_id.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= grandma_id.address %>
  </p>

</div>

app/views/grandma_ids/edit.html.erb
<h1>Editing grandma</h1>

<%= render "form", grandma_id: @grandma_id %>

<br>

<div>
  <%= link_to "Show this grandma", @grandma_id %> |
  <%= link_to "Back to grandmas", grandma_ids_path %>
</div>

app/views/grandma_ids/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Grandmas</h1>

<div id="grandma_ids">
  <% @grandma_ids.each do |grandma_id| %>
    <%= render grandma_id %>
    <p>
      <%= link_to "Show this grandma", grandma_id %>
    </p>
  <% end %>
</div>

<%= link_to "New grandma", new_grandma_id_path %>

app/views/grandma_ids/new.html.erb
<h1>New grandma</h1>

<%= render "form", grandma_id: @grandma_id %>

<br>

<div>
  <%= link_to "Back to grandmas", grandma_ids_path %>
</div>

app/views/grandma_ids/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @grandma_id %>

<div>
  <%= link_to "Edit this grandma", edit_grandma_id_path(@grandma_id) %> |
  <%= link_to "Back to grandmas", grandma_ids_path %>

  <%= button_to "Destroy this grandma", @grandma_id, method: :delete %>
</div>

app/views/grandmas/_info_window.html.erb
<div class="container">
  <div class="row">
    <div class="pop-container">
      <%= image_tag grandma.image_url, class: "pop-up"%>
      <h5><%= grandma.first_name %> <%= grandma.last_name %></h5>
    </div>
  </div>
  <div class="row mt-4">
    <p><%= grandma.location %></p>
  </div>
</div>

app/views/grandmas/index.html.erb
<div class="index-container">
  <div class="row">
    <div class="col-12 col-lg-7 cards-grid">
      <% @grandmas.each do |grandma| %>
        <div class="card">
          <%= link_to grandma , class:"disable_decoration" do %>
            <div class="card-img">
            <% if grandma.image_url.attached? %>
            <%= image_tag grandma.image_url %>
            <% end %>
            </div>
            <div class="card-inner">
              <div class="header">
                <h2><%= grandma.first_name %></h2>
                <h3><%= grandma.skills %></h3>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>


      <div class="col-12 col-lg-5 map-padding">
        <div style="width: 100%; height: 100%;"
          data-controller="map"
          data-map-markers-value="<%= @markers.to_json %>"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>

</div>

app/views/grandmas/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <h1 class="text-center mb-4">Add a new Grandma</h1>
      <%= simple_form_for(@grandma, html: { class: 'form-horizontal' }) do |f| %>
        <div class="form-group">
          <%= f.label :first_name, class: 'control-label' %>
          <%= f.text_field :first_name, class: 'form-control', placeholder: 'Elke'  %>
        </div>
        <div class="form-group">
          <%= f.label :last_name, class: 'control-label' %>
          <%= f.text_field :last_name, class: 'form-control', placeholder: 'Elken'  %>
        </div>
        <div class="form-group">
          <%= f.label :location, class: 'control-label'%>
          <%= f.text_field :location, class: 'form-control', placeholder: 'Berlin' %>
        </div>
        <div class="form-group">
          <%= f.label :description, class: 'control-label' %>
          <%= f.text_area :description, class: 'form-control', placeholder: 'Neat and friendly' %>
        </div>
        <div class="form-group">
          <%= f.label :skills, class: 'control-label'%>
          <%= f.text_field :skills, class: 'form-control', placeholder: 'Tennis' %>
        </div>
          <div class="form-group">
          <%= f.label :price, class: 'control-label' %>
          <%= f.text_field :price, class: 'form-control', placeholder: '55$' %>
        </div>
        <div class="form-group">
         <%= f.input :image_url, as: :file, label: "Choose a profile image", button_text: "Browse for file" %>
        </div>
          <div class="form-group">
           <%= f.input :feed_photos, multiple: true, label: "Choose your skill images", button_text: "Browse for file" %>
          </div>
        <%= f.submit 'Submit', class: 'btn btn-primary btn-block mt-3' %>
      <% end %>
    </div>
  </div>
</div>

app/views/grandmas/show.html.erb
<div class = "container" >
  <div class ="d-flex my-3">
    <h1><%= @grandma.first_name  %> <%= @grandma.last_name  %></h1>
  </div>



  <div class="d-flex images mb-3">
    <%= cl_image_tag @grandma.image_url.key, class: "show-image-left" %>

    <% if @grandma.feed_photos.any? %>
      <div class="show-image-right-container">
        <% @grandma.feed_photos.each do |photo| %>
          <%= cl_image_tag photo.key, class: "show-image-right" %>
        <% end %>
      </div>
    <% end %>
  </div>


<div class="list-group">
    <div >
      <h2>Location:</h2>
      <p class="list-group-item list-group-item-light"><%= @grandma.location %></p>
    </div>

    <div>
      <h2>Skills:</h2>
      <p class="list-group-item list-group-item-light"><%= @grandma.skills %></p>
    </div>

    <div>
      <h2>Description:</h2>
      <p class="list-group-item list-group-item-light" ><%= @grandma.description %></p>
    </div>
</div>

  <div class ="d-flex">

    <%= link_to "Reserve", new_grandma_booking_path(@grandma), class: "btn btn-primary me-3 buttons-show" %>
    <%# <%= link_to "Edit", edit_grandma_path(@grandma), class: "btn btn-primary me-3 buttons-show" %>
    <%# <%= button_to "Delete", grandma_path(@grandma), class: "btn btn-danger buttons-show", method: :delete, data: { confirm: "Are you sure?" } %> 

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Grentma</title>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
<script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
  </head>

  <body>
    <%= render "shared/navbar" unless request.path == "/" %>

    <%= yield %>
    <%= render "shared/footer" unless request.path == "/" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/pages/home.html.erb
<div class="background-grandma">
  <video autoplay muted loop id="bg-video">
    <source src="<%= asset_path('home_page_photos/My project.mp4') %>" type="video/mp4">
  </video>
  <div class="overlay">
    <h1 class="home-header mb-2">Grandmothers and grandchildren were made to meet</h1>
    <h3 class="home-header mb-4">Find the perfect grandmother to experience the feeling of your childhood</h3>
    <div class="button-container">
      <%= link_to "Put your Grandma Online", new_grandma_path, class: "new-grandma-button" %>
      <%= link_to "Live an Experience with a Grandma", grandmas_path, class: "grandmas-button" %>
    </div>
  </div>
</div>



<%# <div class="container">


    <div class="row">
      <div class="col-md-12 text-center">
        <h2 style="
    padding-top: 91px;
">The most Popular Grandmothers</h2>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4 text-center">
        <a href="#">
          <div class="card">
            <img src="/assets/home_page_photos/photo1-9fee0652ef004475aa14639b42a3b552f68fde7e7187050ae51e89a46a73040f.png">
            <div class="card-body">
              <h5 class="card-title">3 Times Pokers World Champion</h5>
              <p class="card-text">Edna Jackson</p>
              <p class="card-text">Cooking, Gardening, Knitting</p>
            </div>
          </div>
        </a>
      </div>
      <div class="col-md-4 text-center">
        <a href="#">
          <div class="card">

            <img src="/assets/home_page_photos/photo2-afcd66e101582961ba83859522f23eb42c57af5457a355f35624958b252a0cde.png">
            <div class="card-body">
              <h5 class="card-title">Former Sniper</h5>
              <p class="card-text">Rose Miller</p>
              <p class="card-text">Baking, Storytelling, Sewing</p>
            </div>
          </div>
        </a>
      </div>
      <div class="col-md-4 text-center">
        <a href="#">
          <div class="card">
            <img src="/assets/home_page_photos/photo3-1c79bf5392a4d611b3b2ff9f44e4d9dab8d4b3dc629ec8745bfff086664f7c33.png">
            <div class="card-body">
              <h5 class="card-title">Former Female Rapper</h5>
              <p class="card-text">Katana Johnson</p>
              <p class="card-text">Knitting, Crocheting, Cooking</p>
            </div>
          </div>
        </a>
      </div>
    </div> %>

app/views/shared/_footer.html.erb
<div class="footer mt-4 mb-5">
  <div class="text-left">
    <p>2023 grentma, Inc. - Datenschutz - Nutzungsbedingungen - Sitemap - Angaben zum Unternehmen</p>
  </div>
  <div class="text-right">
    <p>Deutsch (DE) Währung auswählen</p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<!-- Navbar -->
<nav class="navbar navbar-light" style="background-color: #D490BF;">
  <div class="container-fluid">
    <%= image_tag "home_page_photos/Component 2.png", style: "width:10%" %>

<div class="mx-auto">
      <div class="form-group">
        <a button class="btn btn-info" href="#searchModal" data-bs-toggle="modal" class="form-control" aria-describedby="emailHelp">Find your Grandma</a>
      </div>
    </div>
     <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <li class="nav-item dropdown">
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", "#", class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
          <li class="nav-item active">
            <%= link_to "Home", grandmas_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Rent-a-grandma", new_grandma_path, class: "nav-link" %>
          </li>
            <li class="nav-item">
            <%= link_to "Messages", new_grandma_path, class: "nav-link" %>
          </li>
            <li class="nav-item">
            <%= link_to "Edit profile", new_grandma_path, class: "nav-link" %>
          </li>
      </ul>
    </div>
  </div>

</nav>

<!-- Search modal code -->
<div class="modal fade" id="searchModal" tabindex="-1" aria-labelledby="searchModalLabel" aria-hidden="true">
  <div class="modal-dialog">

    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Search for a Grandma</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="container">
          <div class="search">
            <%= form_tag search_grandmas_path, method: :get do %>
              <div class="row">
                <div class="col-md-12">
                  <div class="search-1">
                    <i class='bx bx-search-alt'></i>
                    <%= text_field_tag :query, nil, class: "form-control form-control-lg", placeholder: "Search for a Grandma" %>
                  </div>
                </div>
              </div>
              <div class="row mt-2">
                <div class="col-md-12">
                  <%= submit_tag "Search", class: "btn btn-info btn-lg w-100" %>
                </div>
              </div>
            <% end %>
          </div>
    </div>
        </div>
      </div>
    </div>
  </div>
</div>